### ISSUE TITLE
After upgrading to 0.6.1, emoji skype doesn't appear to be working

### ISSUE THREAD

**Issue by approxinfinity** [julianlam/nodebb-plugin-emoji-skype#8]
Hi Julian. I upgraded to nodebb 0.6.1 and now emoji skype doesn't appear to be working anymore. Particularly, we were trying to (puke).

**Comment by julianlam** [comment]
Ha, I didn't know people used this plugin! Awesome. Let me update it for you now.

**Comment by julianlam** [comment]
Closed via 89a6f98

Please install v1.0.0 of the plugin :smile:
